name: End to End Tests

on: pull_request

jobs:
  run-backstop-tests:
    runs-on: ubuntu-latest
    container: compucorp/civicrm-buildkit:1.1.0-php7.2-chrome

    env:
      SITE_FOLDER: site
      SITE_URL: http://localhost:7979
      CIVICRM_EXTENSIONS_DIR: web/sites/all/modules/civicrm/tools/extensions
      E2E_DIR: cases-product-suite-e2e-tests
      DRUPAL_THEME_DIR: web/sites/all/themes

    steps:
     - name: Download Compuclient
        run: |
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/compucorp/compuclient.git
